// <auto-generated />
using System;
using MeetingManagementInfrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeetingManagementInfrastructure.Migrations
{
    [DbContext(typeof(MeetingDbContext))]
    [Migration("20251116062851_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeetingManagementDomain.Entities.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("MeetingManagementDomain.Entities.Resolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("UserId");

                    b.ToTable("Resolutions");
                });

            modelBuilder.Entity("MeetingManagementDomain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cd3252f7-f18c-4b21-9a50-c54b58688e58"),
                            CreatedAt = new DateTime(2025, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gmail.com",
                            FirstName = "امیر",
                            LastName = "عزیزی",
                            Password = "$2a$11$PApAaAqms9uDUO5iRKiNce8sYcVSg4wxBSho1AUbNtiiQjl/9R67.",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2025, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7b9684f9-51d1-423f-8666-b51c55d95918"),
                            CreatedAt = new DateTime(2025, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ali@gmail.com",
                            FirstName = "علی",
                            LastName = "منصوری",
                            Password = "$2a$11$L4mbMrzlIbCGfoDxS3Q.H.vBlMXf4zipRi7axon5SXVbNEuqXvIlW",
                            Role = "Member",
                            UpdatedAt = new DateTime(2025, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d3a3b7fb-b599-4647-b059-306625200570"),
                            CreatedAt = new DateTime(2025, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mohammad@gmail.com",
                            FirstName = "محمد",
                            LastName = "مقدسی",
                            Password = "$2a$11$57s53U4BtYwe6SrCZraP7u1JWycYZToWC9M5NNkBw9G58qhXl7hUO",
                            Role = "Member",
                            UpdatedAt = new DateTime(2025, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("769b400f-aeec-4669-9784-e7a3ebf7fccb"),
                            CreatedAt = new DateTime(2025, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hassan@gmail.com",
                            FirstName = "حسن",
                            LastName = "احسانی",
                            Password = "$2a$11$K9/BW2vLSJzDhIxpbLvkreFEipNpKSy4GLlkD1fvuR8J7jltaduV2",
                            Role = "Member",
                            UpdatedAt = new DateTime(2025, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MeetingManagementDomain.Entities.Resolution", b =>
                {
                    b.HasOne("MeetingManagementDomain.Entities.Meeting", "Meeting")
                        .WithMany("Resolutions")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetingManagementDomain.Entities.User", "AssignedTo")
                        .WithMany("AssignedResolutions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("MeetingManagementDomain.Entities.Meeting", b =>
                {
                    b.Navigation("Resolutions");
                });

            modelBuilder.Entity("MeetingManagementDomain.Entities.User", b =>
                {
                    b.Navigation("AssignedResolutions");
                });
#pragma warning restore 612, 618
        }
    }
}
